name: Manual workflow

on:
  repository_dispatch:
    types: [games-stats]
    inputs:
      game:
        description: 'Game to update stats'
        required: true
        default: ''
      winner:
        description: 'Winner of the game'
        required: true
        default: ''

jobs:
  qpokemon:
    name: Update qpokemon stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        
    - name: Create local changes
      run: |
        cd games
        python update-stats.py "${{ github.event.client_payload.game }}" "${{ github.event.client_payload.winner }}"
        cat stats/*
        
