name: Qpokemon team stats

on:
  repository_dispatch:
    types: [qpokemon-team-stats]
    inputs:
      winner:
        description: 'Winner team'
        required: true
        default: ''
      looser:
        description: 'Looser team'
        required: true
        default: ''

jobs:
  update-stats:
    name: Update Qpokemon team stats
    concurrency: ci-qpokemon-team
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: preview
      run: |
        for i in "${{ github.event.client_payload.winner }}"; do
          echo "$i"
        done

    - name: Update csv
      run: |
        cd games

        declare -a win=${{ github.event.client_payload.winner }}
        for i in "${win[@]}"; do
          python qpokemon_team-stats.py "$i" "yes"
        done

        declare -a loo=${{ github.event.client_payload.looser }}
        for i in "${loo[@]}"; do
          python qpokemon_team-stats.py "$i" "no"
        done

    - name: Pull modif
      run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update stats for ${{ github.event.client_payload.game }}
